### ISSUE TITLE
Breaking changes in version v1.1 -> v1.2

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/DynamicalSystemsBase.jl#81]
Probably related to dependencies of packages for differential equations, which have changed from v1.1 to v1.2.x.

Noticed this when trying to fix https://github.com/JuliaDynamics/DelayEmbeddings.jl/issues/18
The code snippet there:

```julia
using DynamicalSystems
ds = Systems.gissinger(ones(3)) # 3D continuous chaotic system, also shown in orbit diagrams tutorial
dt = 0.05
data = trajectory(ds, 1000.0, dt = dt)
```

... produced the following with `DynamicalSystemsBase` v.1.1.1:
```
3-dimensional Dataset{Float64} with 20001 points
  1.0       1.0       1.0      
  0.953553  1.04482   1.04384  
  0.90227   1.08889   1.08512  
  0.846142  1.13164   1.12344  
  0.785246  1.17243   1.15838  
  0.719745  1.21067   1.18952  
  0.649903  1.24574   1.21643  
  0.576079  1.27708   1.23872  
  0.498731  1.30417   1.25602  
  0.418402  1.32655   1.26807  
  ⋮                            
 -1.49076   0.595225  0.0120852
 -1.50002   0.591354  0.0121206
 -1.50933   0.587493  0.0121694
 -1.51869   0.583642  0.012232 
 -1.52811   0.579798  0.0123093
 -1.53759   0.575962  0.0124017
 -1.54712   0.572131  0.01251  
 -1.55672   0.568305  0.0126351
 -1.56637   0.564481  0.0127779
```

But after updating to v.1.2.2+ (actually to d3b0aec9b), the result of the same code yields:
```
3-dimensional Dataset{Float64} with 20001 points
  1.0       1.0       1.0     
  0.953553  1.04482   1.04384 
  0.90227   1.08889   1.08512 
  0.846142  1.13164   1.12344 
  0.785246  1.17243   1.15838 
  0.719745  1.21067   1.18952 
  0.649903  1.24574   1.21643 
  0.576079  1.27708   1.23872 
  0.498731  1.30417   1.25602 
  0.418402  1.32655   1.26807 
  ⋮                           
 -1.03827   1.1142   -0.219919
 -1.03209   1.12004  -0.2217  
 -1.02572   1.12587  -0.223345
 -1.01915   1.13169  -0.224846
 -1.0124    1.13747  -0.226194
 -1.00548   1.14321  -0.227381
 -0.998378  1.1489   -0.2284  
 -0.991119  1.15452  -0.229242
 -0.983709  1.16007  -0.2299  
``` 

That's the problem of chaos! :worried:

**Comment by heliosdrm** [comment]
To follow SemVer, either the package should be tagged as 2.0, or the dependencies should be reverted to the ones used in 1.1. This is at least breaking the tests of `DelayEmbeddings` (cf. https://github.com/JuliaDynamics/DelayEmbeddings.jl/issues/20)  and perhaps other packages.

**Comment by Datseris** [comment]
oh damn it... I didn't forsee this. Yeah in 1.2 we changed the default solver. You think we should make the version 2.0?

You can use the previous solver by adding `using OrdinaryDiffEq` and do `trajectory(ds, ...; alg = Vern9())`

**Comment by heliosdrm** [comment]
After, re-reading, I think you may be right in https://github.com/JuliaDynamics/DelayEmbeddings.jl/issues/20#issuecomment-461968969. If the API does not change, might be left as minor change.

I wonder though: if it is possible to do `trajectory(ds, ...; alg = Vern9())` and get the same result as before, perhaps it would be advisable to make that the default option in order to stick to the concept of "backward-compatible added functionality"?

If the problem is that such older behavior is slower or heavier, it might be documented and advised to do it in another way, maybe introducing a deprecation now or later on (deprecations in minor versions are ok).

**Comment by Datseris** [comment]
Normally I would do what you said without a second thought. But there is one and only one reason for this change (changing the default solver).

The `OrdinaryDiffEq` dependency is dropped, which means it is not installed nor precompiled when `using DynamicalSystems`. Now, this is a huge benefit because the "first run time" is reduced significantly and the "snappyness" of the package is overall greater.

In addition, the compile times of advanced functions (like e.g. `lyapunovs`) change from 25 seconds (!!!!) to 8 seconds. Which is of course huge. 

These are the reasons that I'd like to move everything to the new default solver, i.e. `SimpleATsit5`.

**Comment by heliosdrm** [comment]
Fine. So: minor version change with the corresponding documentation about the better and faster integration, but inevitably different results?

**Comment by Datseris** [comment]
> Fine. So: minor version change with the corresponding documentation about the better and faster integration, but inevitably different results?

Yeap. As I said, it is actually a very unfortunate event that you got caught up into this... The new documentation is actually _already_ written. And the new version of `DynamicalSystems` opens up with a warning message as well! (pretty cool!)

The only reason you don't see these things yet is because I am in the middle of updating `ChaosTools`... But I will definitely be done with this over the weekend!
