### ISSUE TITLE
Change reinit! behaviour for in-place parallel integrator of CDSs

### ISSUE THREAD

**Issue by efosong** [JuliaDynamics/DynamicalSystemsBase.jl#84]
Trying to keep code 'generic', we may wish to `reinit!` a parallel integrator as follows

```julia
p_integ = parallel_integrator(ds_inplace, [u0, u1])
# other code...
reinit!(p_integ, [u2, u3])
```
However, for in-place `ContinuousDynamicalSystem`, the state of `p_integ` has type `Array{Float64, 2}` so this use of `reinit!` fails when the usual `Array{Array{Float64, 1}, 1}` is passed.

I propose adding a check to `reinit!` (or an extra dispatch) which passes the `Array{Array{Float64, 1}}` through `hcat` to yield an `Array{Float64, 2}` first if the dynamical system is continuous and defined in-place. This way, code can be written more generically without having to handle the special case of in-place CDSs.

It's possible to check both conditions like this

```julia
typeof(ds) <: ContinuousDynamicalSystem && isinplace(ds)
```
Perhaps there's a nicer way to do it via type dispatch.

**Comment by efosong** [comment]
My initial thought was to do something like:
```julia
function DiffEqBase.reinit!(integ::DiffEqBase.AbstractODEIntegrator{A,B,Array{T,2},C}, 
							u0::Array{Array{T,1},1}; kwargs...
							) where A where B where C where T
	u0 = hcat(u0...)
    set_state!(integ, u0)
    set_deviations!(integ, Q0)
    reinit!(integ, integ.u; kwargs...)
end
```

However
1. I think this is 'type piracy', which should probably be avoided in general but might be fine in this case
2. There is an ambiguous dispatch:
```
[...] is ambiguous. Candidates:
  reinit!(integ::DiffEqBase.AbstractODEIntegrator{A,B,Array{T,2},C}, u0::Array{Array{T,1},1}) where {T, C, B, A} in Main at ~/test/dynamical_systems/neuron.jl:68
  reinit!(integrator::SimpleDiffEq.SimpleATsit5Integrator, u0) in SimpleDiffEq at ~/.julia/packages/SimpleDiffEq/VvzwD/src/tsit5/atsit5.jl:566
Possible fix, define
  reinit!(::SimpleDiffEq.SimpleATsit5Integrator{B,Array{T,2},C,P,F,N} where N where F where P, ::Array{Array{T,1},1})
```
But it would be nice to avoid having to define this for each possible `SimpleIntegrator`.

**Comment by Datseris** [comment]
Typically the parallel integrator has as state a `Vector{SVector}` for out of place systems. For in-place _discrete_ systems it has `Vector{Vector}`. In place continuous systems are the only ones where internally the state is represented as a `Matrix`, with each column one state. 

The reason I had to do this is because (when writing **DynamicalSystems.jl**) there was a significant performance drop in DiffEq when one used a `Vector{Vector}` instead of `Matrix`. This was some while ago so I think I should ask @ChrisRackauckas whether this is still a problem. 

Let's wait for his answer before looking at this issue in more detail. In the meantime I will take the liberty of changing your issue title, because it really appears specific to the parallel integrator, and not the generic CDS.

**Comment by ChrisRackauckas** [comment]
`Vector{Vector}` doesn't recurse broadcast or its norm, so it's not actually a "vector" if you want the numbers to be its element types. Use VectorOfArray from RecursiveArrayTools (it may need to recurse its broadcast like ArrayPartition)
